config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :consulta
  resources :medicos
  resources :pacientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/paciente.rb
class Paciente < ApplicationRecord
  has_many :consultums
  has_one :endereco, :dependent => :destroy

  accepts_nested_attributes_for :endereco, update_only: true, allow_destroy: true

  validates :nome, presence: true, length: { in: 8..50 },format: { with: /[a-zA-Z]+/, message: "only allows letters" }, format: { with: /\s/ }
  validates :cpf, presence: true, length: { is: 11 }, uniqueness: true, format: { with: /[\d]+/, message: "only allow numbers" }
  validates :email, presence: true, length: { minimum: 4 }, format: { with: /[a-z0-9.]+@[a-z0-9]+\.[a-z]+(\.[a-z]+)?/ }
  validates :nascimento, presence: true, in_future: false
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    @paciente.build_endereco
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes or /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully created." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1 or /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1 or /pacientes/1.json
  def destroy
    @paciente.destroy

    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paciente_params
      params.require(:paciente).permit(:nome, :nascimento, :cpf, :email, :endereco_attributes => [:cep, :cidade, :bairro, :logradouro, :complemento])
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :nascimento, style: "display: block" %>
    <%= form.date_field :nascimento %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <%= form.fields_for :endereco do |fend| %>
    <div>
      <%= fend.label :logradouro, style: "display: block" %>>
      <%= fend.text_field :logradouro %>
    </div>

    <div>
      <%= fend.label :bairro, style: "display: block" %>>
      <%= fend.text_field :bairro %>
    </div>

    <div>
      <%= fend.label :cidade, style: "display: block" %>>
      <%= fend.text_field :cidade %>
    </div>

    <div>
      <%= fend.label :cep, style: "display: block" %>>
      <%= fend.text_field :cep %>
    </div>

    <div>
      <%= fend.label :complemento, style: "display: block" %>>
      <%= fend.text_field :complemento %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/_paciente.html.erb
<div id="<%= dom_id paciente %>">
  <div class="card">
    <strong style="font-size: 1rem">Nome:</strong>
    <%= paciente.nome %><br/><br/>

    <strong style="font-size: 1rem">Cpf:</strong>
    <%= paciente.cpf %><br/><br/>

    <strong style="font-size: 1rem">Email:</strong>
    <%= paciente.email %><br/><br/>

    <strong style="font-size: 1rem">Nascimento:</strong>
    <%= paciente.nascimento %><br/><br/>

    <strong style="font-size: 1rem">Endereço:</strong>
    <div class="card">
      <strong style="font-size: 1rem">Logradouro:</strong>
      <%= paciente.endereco.logradouro %><br/><br/>

      <strong style="font-size: 1rem">Bairro:</strong>
      <%= paciente.endereco.bairro %><br/><br/>

      <strong style="font-size: 1rem">Cidade:</strong>
      <%= paciente.endereco.cidade %><br/><br/>

      <strong style="font-size: 1rem">Cep:</strong>
      <%= paciente.endereco.cep %><br/><br/>

      <strong style="font-size: 1rem">Complemento:</strong>
      <%= paciente.endereco.complemento %><br/><br/>
    </div>
  </div>
</div>

app/views/pacientes/edit.html.erb
<h1>Editing paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Show this paciente", @paciente %> |
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="margin-left: 1rem">Pacientes</h1>
<span class="button" style="display: table; margin: 0 auto; margin-bottom: 5px;">
  <%= link_to "Cadastrar paciente", new_paciente_path %>
</span>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Cpf</th>
    <th>Data de nascimento</th>
    <th>Endereço</th>
    <th>Ações</th>
  </tr>
    <% @pacientes.each do |paciente| %>
    <tr>
      <td>
        <%= paciente.nome %>
      </td>
      <td>
        <%= paciente.email %>
      </td>
      <td>
        <%= paciente.cpf %>
      </td>
      <td>
        <%= paciente.nascimento.strftime("%d/%m/%Y") %>
      </td>
      <td>
        <%= paciente.endereco.logradouro %>, <%= paciente.endereco.bairro %>, <%= paciente.endereco.cidade %>
      </td>
      <td>
        <span class="button">
          <%= link_to "Exibir este paciente", paciente %>
        </span>
      </td>
    </tr>
  <% end %>
</table>

app/views/pacientes/new.html.erb
<h1>New paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paciente %>

<div class="button-container">
  <span class="button">
    <%= link_to "Editar paciente", edit_paciente_path(@paciente) %>
  </span>
  <span class="button">
    <%= link_to "Voltar para pacientes", pacientes_path %>
  </span>
</div>

<hr>
<h2>
  Consultas
</h2>
<table>
  <tr>
    <th>Medico</th>
    <th>Data</th>
    <th>Horário</th>
  </tr>
  <% Consultum.where(paciente_id: @paciente.id).each do |consulta| %>
    <tr id="<%=consulta.id%>" class="consultumRow">
      <td>
        <%= Medico.find(consulta.medico_id).nome %>
      </td>
      <td>
        <%= consulta.data.strftime("%d/%m/%Y") %>
      </td>
      <td>
        <%= consulta.horario %>
      </td>
    </tr>
  <% end %>
</table>