config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :consulta
  resources :medicos
  resources :pacientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/controllers/consulta_controller.rb
class ConsultaController < ApplicationController
  before_action :set_consultum, only: %i[ show edit update destroy ]

  # GET /consulta or /consulta.json
  def index
    @consulta = Consultum.all
  end

  # GET /consulta/1 or /consulta/1.json
  def show
  end

  # GET /consulta/new
  def new
    @consultum = Consultum.new
  end

  # GET /consulta/1/edit
  def edit
  end

  # POST /consulta or /consulta.json
  def create
    @consultum = Consultum.new(consultum_params)

    respond_to do |format|
      if @consultum.save
        format.html { redirect_to consultum_url(@consultum), notice: "Consultum was successfully created." }
        format.json { render :show, status: :created, location: @consultum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consulta/1 or /consulta/1.json
  def update
    respond_to do |format|
      if @consultum.update(consultum_params)
        format.html { redirect_to consultum_url(@consultum), notice: "Consultum was successfully updated." }
        format.json { render :show, status: :ok, location: @consultum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consulta/1 or /consulta/1.json
  def destroy
    @consultum.destroy

    respond_to do |format|
      format.html { redirect_to consulta_url, notice: "Consultum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultum
      @consultum = Consultum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultum_params
      params.require(:consultum).permit(:paciente_id, :medico_id, :data, :horario)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/views/consulta/_consultum.html.erb
<div id="<%= dom_id consultum %>">
  <div class="card">
    <strong style="font-size: 1rem">Paciente:</strong>
    <%= Paciente.find(consultum.paciente_id).nome %><br/><br/>

    <strong style="font-size: 1rem">Medico:</strong>
    <%= Medico.find(consultum.medico_id).nome %><br/><br/>

    <strong style="font-size: 1rem">Data:</strong>
    <%= consultum.data.strftime("%d/%m/%Y") %><br/><br/>

    <strong style="font-size: 1rem">Horario:</strong>
    <%= consultum.horario %>
  </div>
</div>

app/views/consulta/_form.html.erb
<%= form_with(model: consultum) do |form| %>
  <% if consultum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(consultum.errors.count, "error") %> prohibited this consultum from being saved:</h2>

      <ul>
        <% consultum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.collection_select(:paciente_id, Paciente.all, :id, :nome) %>
  </div>

  <div>
    <%= form.collection_select(:medico_id, Medico.all, :id, :nome) %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.text_field :horario %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/consulta/edit.html.erb
<h1>Editing consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Show this consultum", @consultum %> |
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="margin-left: 1rem">Consultas</h1>

<span class="button" style="display: table; margin: 0 auto; margin-bottom: 5px;">
  <%= link_to "Agendar consulta", new_consultum_path %>
</span>

<table>
  <tr>
    <th>Paciente</th>
    <th>Medico</th>
    <th>Data</th>
    <th>Horário</th>
    <th>Ações</th>
  </tr>
    <% @consulta.each do |consultum| %>
    <tr>
      <td>
        <%= Paciente.find(consultum.paciente_id).nome %>
      </td>
      <td>
        <%= Medico.find(consultum.medico_id).nome %>
      </td>
      <td>
        <%= consultum.data.strftime("%d/%m/%Y") %>
      </td>
      <td>
        <%= consultum.horario %>
      </td>
      <td>
        <span class="button">
          <%= link_to "Exibir esta consulta", consultum %>
        </span>
      </td>
    </tr>
  <% end %>
</table>

app/views/consulta/new.html.erb
<h1>New consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @consultum %>

<div class="button-container">
  <span class="button">
    <%= link_to "Voltar para consultas", consulta_path %>
  </span>
</div>