config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :consulta
  resources :medicos
  resources :pacientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/medico.rb
class Medico < ApplicationRecord
  has_many :consultums

  validates :nome, presence: true, length: { in: 8..50 },format: { with: /[a-zA-Z]+/, message: "only allows letters" }, format: { with: /\s/ }
  validates :cpf, presence: true, length: { is: 11 }, uniqueness: true, format: { with: /[\d]+/, message: "only allow numbers" }
  validates :email, presence: true, length: { minimum: 4 }, format: { with: /[a-z0-9.]+@[a-z0-9]+\.[a-z]+(\.[a-z]+)?/ }
  validates :crm, presence: true, numericality: { only_integer: true }, length: { is: 6 }
  validates :especialidade, presence: true, length: { minimum: 4 }, format: { with: /[a-zA-Z]+/, message: "only allows letters" }
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: %i[ show edit update destroy ]

  # GET /medicos or /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1 or /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos or /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully created." }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1 or /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully updated." }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1 or /medicos/1.json
  def destroy
    @medico.destroy

    respond_to do |format|
      format.html { redirect_to medicos_url, notice: "Medico was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medico_params
      params.require(:medico).permit(:cpf, :nome, :email, :especialidade, :crm)
    end
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/_form.html.erb
<%= form_with(model: medico) do |form| %>
  <% if medico.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
        <% medico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :especialidade, style: "display: block" %>
    <%= form.text_field :especialidade %>
  </div>

  <div>
    <%= form.label :crm, style: "display: block" %>
    <%= form.text_field :crm %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/_medico.html.erb
<div id="<%= dom_id medico %>">
  <div class="card">
    <strong style="font-size: 1rem">Nome:</strong>
    <%= medico.nome %><br/><br/>

    <strong style="font-size: 1rem">Cpf:</strong>
    <%= medico.cpf %><br/><br/>

    <strong style="font-size: 1rem">Email:</strong>
    <%= medico.email %><br/><br/>

    <strong style="font-size: 1rem">Especialidade:</strong>
    <%= medico.especialidade %><br/><br/>

    <strong style="font-size: 1rem">Crm:</strong>
    <%= medico.crm %>
  </div>
</div>

app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Show this medico", @medico %> |
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="margin-left: 1rem">Medicos</h1>
<span class="button" style="display: table; margin: 0 auto; margin-bottom: 5px;">
  <%= link_to "New medico", new_medico_path %>
</span>
<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Cpf</th>
    <th>Crm</th>
    <th>Especialidade</th>
    <th>Ações</th>
  </tr>
    <% @medicos.each do |medico| %>
    <tr>
      <td>
        <%= medico.nome %>
      </td>
      <td>
        <%= medico.email %>
      </td>
      <td>
        <%= medico.cpf %>
      </td>
      <td>
        <%= medico.crm %>
      </td>
      <td>
        <%= medico.especialidade %>
      </td>
      <td>
        <span class="button">
          <%= link_to "Show this medico", medico %>
        </span>
      </td>
    </tr>
  <% end %>
</table>

app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medico %>

<div class="button-container">
  <span class="button">
    <%= link_to "Editar medico", edit_medico_path(@medico) %>
  </span>
  <span class="button">
    <%= link_to "Voltar para medicos", medicos_path %>
  </span>
</div>

<hr>
<h2 style="margin-left: 1rem">
  Consultas
</h2>
<table>
  <tr>
    <th>Paciente</th>
    <th>Data</th>
    <th>Horário</th>
  </tr>
    <% Consultum.where(medico_id: @medico.id).each do |consulta| %>
      <tr>
        <td>
          <%= Paciente.find(consulta.paciente_id).nome %>
        </td>
        <td>
          <%= consulta.data.strftime("%d/%m/%Y") %>
        </td>
        <td>
          <%= consulta.horario %>
        </td>
      </tr>
    <% end %>
</table>